---

- hosts: "{{ hosts }}"
  become: true
  vars:
    config_dir: "{{ lookup('ini', 'COMMON_SCRIPTS section=ANSIBLE file={{ configFile }}')}}/config"
    software_dir: "{{ lookup('ini', 'CONNECT_SOFTWARE_LIN section=Common_Settings file={{ configFile }}') }}"
    db_zip_one: "{{ lookup('ini', 'SOFTWARE_SOURCE section=Common_Settings file={{ configFile }}') }}/Database/{{ lookup('ini', 'DB_ZIP_SRC_ONE section=ORA file={{ configFile }}') }}"
    db_zip_two: "{{ lookup('ini', 'SOFTWARE_SOURCE section=Common_Settings file={{ configFile }}') }}/Database/{{ lookup('ini', 'DB_ZIP_SRC_TWO section=ORA file={{ configFile }}') }}"
    install_response_file: "{{ lookup('ini', 'INSTALL_RESPONSE_SRC section=ORA file={{ configFile }}') }}"
    config_response_file: "{{ lookup('ini', 'CONFIG_RESPONSE_SRC section=ORA file={{ configFile }}') }}"
    install_shell_script: "{{ lookup('ini', 'ORACLE_INSTALL_SHELL_SCRIPT section=ORA file={{ configFile }}') }}"
    oracle_password: "{{ lookup('ini', 'ORACLE_PASSWORD section=ORA file={{ configFile }}') }}"
    oracle_password: "{{ oracle.password }}"
    oracle_home: "{{ lookup('ini', 'ORACLE_HOME section=ORA file={{ configFile }}') }}"
    oracle_base: "{{ lookup('ini', 'ORACLE_BASE section=ORA file={{ configFile }}') }}"
    inventory_location: "{{ lookup('ini', 'INVENTORY_LOCATION section=ORA file={{ configFile }}') }}"
    db_global_name: "{{ lookup('ini', 'DATABASE_GLOBAL_NAME section=ORA file={{ configFile }}') }}"
    sid: "{{ lookup('ini', 'SID section=ORA file={{ configFile }}') }}"
    memory_allocation: "{{ lookup('ini', 'MEMORY_ALLOCATION section=ORA file={{ configFile }}') }}"
    oracle_data_location: "{{ lookup('ini', 'ORACLE_DATA_LOCATION section=ORA file={{ configFile }}') }}"
  tasks:

    - name: Creating devops directory
      file:
        path: "{{ software_dir }}"
        state: directory
        mode: u=rwx,g=rwx,o=rwx
        
    - name: Copy database zips to the server
      copy:
        src: "{{ item }}"
        dest: "{{ software_dir }}/"
      with_items:
        - "{{ db_zip_one }}"
        - "{{ db_zip_two }}"

    - name: Copy scripts to be ran
      copy:
        src: "{{ item }}"
        dest: "{{ software_dir }}/"
      with_items:
        - "{{ config_dir }}/{{ install_response_file }}"
        - "{{ config_dir }}/{{ config_response_file }}"
        - "{{ install_shell_script }}"
      tags:
        - copy

    - name: Replace placeholders in response file
      shell: "sed -i 's|{{ placeholder.oracle_home }}|{{ value.oracle_home }}|g; s|{{ placeholder.oracle_password }}|{{ value.oracle_password }}|g; s|{{ placeholder.oracle_base }}|{{ value.oracle_base }}|g; s|{{ placeholder.inventory_location }}|{{ value.inventory_location }}|g; s|{{ placeholder.db_global_name }}|{{ value.db_global_name }}|g; s|{{ placeholder.sid }}|{{ value.sid }}|g; s|{{ placeholder.memory_allocation }}|{{ value.memory_allocation }}|g; s|{{ placeholder.oracle_data_location }}|{{ value.oracle_data_location }}|g' '{{ software_dir }}/{{ install_response_file }}'"
      vars:
        placeholder: 
          oracle_home: "<ORACLE_HOME>"
          oracle_password: "<ORACLE_PASSWORD>"
          oracle_base: "<ORACLE_BASE>"
          inventory_location: "<INVENTORY_LOCATION>"
          db_global_name: "<DATABASE_GLOBAL_NAME>"
          sid: "<SID>"
          memory_allocation: "<MEMORY_ALLOCATION>"
          oracle_data_location: "<ORACLE_DATA_LOCATION>"
        value: 
#          oracle_password: "{{ lookup('ini', 'ORACLE_PASSWORD section=ORA file={{ configFile }}') }}"
          oracle_password: "{{ oracle_password }}"
          oracle_home: "{{ lookup('ini', 'ORACLE_HOME section=ORA file={{ configFile }}') }}"
          oracle_base: "{{ lookup('ini', 'ORACLE_BASE section=ORA file={{ configFile }}') }}"
          inventory_location: "{{ lookup('ini', 'INVENTORY_LOCATION section=ORA file={{ configFile }}') }}"
          db_global_name: "{{ lookup('ini', 'DATABASE_GLOBAL_NAME section=ORA file={{ configFile }}') }}"
          sid: "{{ lookup('ini', 'SID section=ORA file={{ configFile }}') }}"
          memory_allocation: "{{ lookup('ini', 'MEMORY_ALLOCATION section=ORA file={{ configFile }}') }}"
          oracle_data_location: "{{ lookup('ini', 'ORACLE_DATA_LOCATION section=ORA file={{ configFile }}') }}"
      tags:
        - regex

    - name: Run the script to install oracle
      shell: "sh {{ software_dir }}/{{ install_shell_script }} {{ software_dir }} {{ oracle_password }}"
