---

- hosts: "{{ hosts }}"
  vars:
  tasks:
  - name: Verify if oracle is installed
    shell: sqlplus -version
    register: sqlplus_version
    ignore_errors: true
 
  - name: Print exists message to verify
    debug:
      msg: "Oracle is installed"
    when: sqlplus_version.stdout.find('SQL*Plus') != -1

  - name: Print error message
    debug:
      msg: "Oracle is not installed"
    when: sqlplus_version.stdout.find("SQL*Plus") == -1
